-- Generated by Shpandrak for world

-- Table for entity country
DROP TABLE IF EXISTS country CASCADE;

CREATE TABLE country (
	id uuid NOT NULL,
	name character varying(255) NOT NULL
);

ALTER TABLE country
	ADD CONSTRAINT country_pkey PRIMARY KEY (id);



-- Table for entity animal
DROP TABLE IF EXISTS animal CASCADE;

CREATE TABLE animal (
	id uuid NOT NULL
);

ALTER TABLE animal
	ADD CONSTRAINT animal_pkey PRIMARY KEY (id);



-- Table for entity person
DROP TABLE IF EXISTS t_person CASCADE;

CREATE TABLE t_person (
	id uuid NOT NULL,
	ugly_first_name character varying(255) NOT NULL,
	lastName character varying(255) NOT NULL,
	gender smallint NOT NULL,
	height integer NOT NULL,
	birthDate bigint NOT NULL,
	fatherId uuid,
	motherId uuid,
	birthCountryId uuid NOT NULL
);

ALTER TABLE t_person
	ADD CONSTRAINT t_person_pkey PRIMARY KEY (id);
ALTER TABLE t_person
	ADD CONSTRAINT t_person_father_fk
	 FOREIGN KEY (fatherId) REFERENCES person;ALTER TABLE t_person
	ADD CONSTRAINT t_person_mother_fk
	 FOREIGN KEY (motherId) REFERENCES person;ALTER TABLE t_person
	ADD CONSTRAINT t_person_birthCountry_fk
	 FOREIGN KEY (birthCountryId) REFERENCES country;


-- Relationship table for many-to-many relationship visitCountry between person to country entities
DROP TABLE IF EXISTS t_person_visitCountrys CASCADE;

CREATE TABLE t_person_visitCountrys (
    id uuid NOT NULL,
    personId uuid NOT NULL,
    countryId uuid NOT NULL);

ALTER TABLE t_person_visitCountrys
    ADD CONSTRAINT t_person_visitCountrys_t_person_fk
    FOREIGN KEY (personId) REFERENCES t_person;

ALTER TABLE t_person_visitCountrys
    ADD CONSTRAINT t_person_visitCountrys_related_country_fk
    FOREIGN KEY (countryId) REFERENCES country;



