-- Generated by Shpandrak for world

-- Table for entity country
DROP TABLE IF EXISTS country CASCADE;

CREATE TABLE country (
	id uuid NOT NULL,
	name character varying(255) NOT NULL
);

ALTER TABLE country
	ADD CONSTRAINT country_pkey PRIMARY KEY (id);



-- Table for entity person
DROP TABLE IF EXISTS person CASCADE;

CREATE TABLE person (
	id uuid NOT NULL,
	firstName character varying(255) NOT NULL,
	lastName character varying(255) NOT NULL,
	gender smallint NOT NULL,
	birthDate bigint NOT NULL,
	birthCountryId uuid NOT NULL
);

ALTER TABLE person
	ADD CONSTRAINT person_pkey PRIMARY KEY (id);
ALTER TABLE person
	ADD CONSTRAINT person_country_fk
	 FOREIGN KEY (birthCountryId) REFERENCES country;


-- Relationship table for many-to-many relationship ownsPassportForCountry between person to country entities
DROP TABLE IF EXISTS person_ownsPassportForCountrys CASCADE;

CREATE TABLE person_ownsPassportForCountrys (
    id uuid NOT NULL,
    personId uuid NOT NULL,
    countryId uuid NOT NULL);

ALTER TABLE person_ownsPassportForCountrys
    ADD CONSTRAINT person_ownsPassportForCountrys_person_fk
    FOREIGN KEY (personId) REFERENCES person;

ALTER TABLE person_ownsPassportForCountrys
    ADD CONSTRAINT person_ownsPassportForCountrys_country_fk
    FOREIGN KEY (countryId) REFERENCES country;



